import Link from 'next/link'
import { notFound } from 'next/navigation'
import { digestAPI } from '@/lib/api'
import { WeekBadge } from '@/components/ui/WeekBadge'
import { SourcesPanel } from '@/components/dashboard/SourcesPanel'
import {
  DevelopmentsSection,
  SlackSection,
  ImplicationsSection,
  CompaniesSection,
  JobsSection,
  FeaturedSection,
} from '@/components/dashboard/DigestSection'

export const dynamic = 'force-dynamic'

export default async function DigestPage({ params }: { params: { id: string } }) {
  let digest
  try {
    const res = await digestAPI.getById(params.id)
    digest = res.digest
  } catch {
    notFound()
  }

  const generatedAt = new Date(digest.generated_at).toLocaleString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })

  return (
    <div className="max-w-3xl">
      {/* Back */}
      <Link
        href="/archive"
        className="mb-5 inline-flex min-h-[40px] items-center gap-1 rounded-md px-1 text-xs text-textmuted transition hover:text-textprimary sm:mb-6"
      >
        <span aria-hidden="true">←</span> All Digests
      </Link>

      {/* Header */}
      <div className="mb-6 sm:mb-8">
        <WeekBadge weekNumber={digest.week_number} weekStart={digest.week_start} showOverall className="mb-2" />
        <h1 className="mb-2 font-display text-2xl font-bold leading-tight text-textprimary sm:mb-3 sm:text-3xl">
          {digest.week_start} – {digest.week_end}
        </h1>
        <SourcesPanel digest={digest} />
      </div>

      {/* Summary */}
      <p className="mb-8 border-b border-border pb-7 text-base leading-relaxed text-textprimary/92 sm:mb-10 sm:pb-8 sm:text-lg">
        {digest.week_summary}
      </p>

      {/* Sections */}
      <div className="space-y-8 sm:space-y-10">
        {/* 1. What happened in AI this week */}
        {digest.ai_developments?.length > 0 && (
          <DevelopmentsSection items={digest.ai_developments} />
        )}

        {/* 2. Why this matters for Pursuit */}
        {digest.pursuit_implications?.length > 0 && (
          <ImplicationsSection items={digest.pursuit_implications} />
        )}

        {/* 3. Jobs & workforce shifts */}
        {digest.jobs_and_hiring && (
          <JobsSection data={digest.jobs_and_hiring} />
        )}

        {/* 4. Companies gaining traction in the space */}
        {digest.companies_to_watch?.length > 0 && (
          <CompaniesSection items={digest.companies_to_watch} />
        )}

        {/* 5. Slack team discussions */}
        {digest.slack_highlights && (
          <SlackSection data={digest.slack_highlights} />
        )}

        {/* 6. One article worth Joanna's time */}
        {digest.featured_resource && (
          <FeaturedSection data={digest.featured_resource} />
        )}
      </div>

      {/* Footer */}
      <p className="mt-10 border-t border-border pt-6 font-mono text-xs text-textmuted sm:mt-12">
        Generated by Claude AI <span aria-hidden="true">·</span> {generatedAt}
      </p>
    </div>
  )
}
