import Link from 'next/link'
import { notFound } from 'next/navigation'
import { digestAPI } from '@/lib/api'
import { MOCK_DIGEST } from '@/lib/mock-data'
import { SourceBadge } from '@/components/ui/Badge'
import { WeekBadge } from '@/components/ui/WeekBadge'
import {
  DevelopmentsSection,
  SlackSection,
  ImplicationsSection,
  CompaniesSection,
  JobsSection,
  FeaturedSection,
} from '@/components/dashboard/DigestSection'

export const dynamic = 'force-dynamic'

export default async function DigestPage({ params }: { params: { id: string } }) {
  let digest
  try {
    const res = await digestAPI.getById(params.id)
    digest = res.digest
  } catch {
    // Fall back to mock data for mock IDs; 404 everything else
    if (params.id === MOCK_DIGEST.id) {
      digest = MOCK_DIGEST
    } else {
      notFound()
    }
  }

  const generatedAt = new Date(digest.generated_at).toLocaleString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })

  return (
    <div className="max-w-2xl">
      {/* Back */}
      <Link
        href="/archive"
        className="inline-flex items-center gap-1 text-xs text-textmuted hover:text-textprimary transition mb-6"
      >
        ← All Digests
      </Link>

      {/* Header */}
      <div className="mb-8">
        <WeekBadge weekNumber={digest.week_number} showOverall className="mb-2" />
        <h1 className="font-display text-3xl font-bold text-textprimary mb-2">
          {digest.week_start} – {digest.week_end}
        </h1>
        <div className="flex items-center gap-2 flex-wrap">
          <SourceBadge label={`${digest.external_source_count} external sources`} />
        </div>
      </div>

      {/* Summary */}
      <p className="text-base text-textprimary/90 leading-relaxed mb-10 pb-8 border-b border-border">
        {digest.week_summary}
      </p>

      {/* Sections */}
      <div className="space-y-10">
        {digest.ai_developments?.length > 0 && (
          <DevelopmentsSection items={digest.ai_developments} />
        )}

        {digest.slack_highlights && (
          <SlackSection data={digest.slack_highlights} />
        )}

        {digest.pursuit_implications?.length > 0 && (
          <ImplicationsSection items={digest.pursuit_implications} />
        )}

        {digest.companies_to_watch?.length > 0 && (
          <CompaniesSection items={digest.companies_to_watch} />
        )}

        {digest.jobs_and_hiring && (
          <JobsSection data={digest.jobs_and_hiring} />
        )}

        {digest.featured_resource && (
          <FeaturedSection data={digest.featured_resource} />
        )}
      </div>

      {/* Footer */}
      <p className="mt-12 pt-6 border-t border-border text-xs text-textmuted font-mono">
        Generated by Claude AI · {generatedAt}
      </p>
    </div>
  )
}
